### ISSUE TITLE
gnomad links not working

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#732] opened 2019-02-06 18:31 UTC
Hi Hana, the links out to gnomad haven't been working recently for families in our engle wgs 900 cohort. For example, in this family:

https://seqr.broadinstitute.org/project/R0420_engle_wgs_900/saved_variants/family/F021982_238/Review

Clicking the frequency link to get to gnomad itself gives me a "variant not found" error:
https://gnomad.broadinstitute.org/variant/12-120127695-G-T

Thanks!

**Comment by hanars** [comment] 2019-02-06 18:51
Hi Julie,

The gnomad browser has been updated to the latests gnomad callset, however seqr is still using the last version. This means there is some discrepancy between the allele counts/ frequencies displayed in seqr and those in the gnomad browser. In this particular case if you look at that region in the gnomad browser you will see that there are no variants at the position you were looking at: https://gnomad.broadinstitute.org/region/12-120127675-120127715

Unfortunately, this is not an easy thing to fix. It requires updates to the seqr loading pipeline that are actively being worked on but will not be done for a couple more months. Thank you for your patience.

**Comment by hanars** [comment] 2019-02-26 19:02
Hi Julie,

I was wrong about the cause of this, it was an actually an issue with the links being computed using build 38 coordinates but gnomad urls expecting build 37 coordinates. This should be fixed now

**Closed by hanars** 2019-02-26 19:02 UTC
Labels: bug
