### ISSUE TITLE
Unpair option for each gene

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1266] opened 2020-04-27 16:51 UTC
It's great we have the option to unpair variants among the search results. However, some genes are just messy and result in a ton if combinations. Unpairing at the top undoes the pairs for all genes. So in addition to the unpair option at the top, can we also have it for a specific gene? 
This way I can choose unpair for specific genes if they are too many combinations, while keeping the option for other genes. 
![Screen Shot 2020-04-27 at 12 47 27 PM](https://user-images.githubusercontent.com/37872186/80398493-b233f980-8885-11ea-8476-f5533a45abe6.png)

**Comment by hanars** [comment] 2020-04-27 17:05
Duplicate of https://github.com/macarthur-lab/seqr-private/issues/787

**Closed by hanars** 2020-04-27 17:05 UTC
Labels: feature request
