### ISSUE TITLE
gcloud error: 'There was a problem refreshing your current auth tokens' (CentOS7 VM)

### ISSUE THREAD

**Issue by puapinyoying** [macarthur-lab/seqr#597] opened 2018-10-04 18:26 UTC
Hi Ben,

I am having trouble installing Seqr on my CentOS7 VM due to this error that crops up when deploying seqr in minikube. I am using a MacBook Pro with 16gb ram and 4 cores running 10.13.6 High Sierra.  CentOS7 is installed in a VM using Parallels.  

**VM specs:**
- 2 processors
- 8 gb ram (I know its lower than your minimum, but I plan to deploy the VM onto a more powerful machine later on)
- 256 gb hdd

I followed your instructions without a hitch for steps 1-3 for the CentOS install.  But ran into an issue with missing google cloud sdk (your steps don't include that in the install scripts). So I manually installed it.

Afterwards, I would run into this issue where Seqr would never enter a ready state.

```bash
2018-10-04 14:07:03,605 INFO     seqr is_ready status = false
2018-10-04 14:07:08,687 INFO     seqr is_ready status = false
2018-10-04 14:07:13,783 INFO     seqr is_ready status = false
2018-10-04 14:07:18,877 INFO     seqr is_ready status = false
2018-10-04 14:07:23,970 INFO     seqr is_ready status = false
```

Looking into this a bit further it looked like there was an issue with gcloud using your provided account-key:

```bash
./servctl logs seqr minikube
...
2018-10-04 13:54:42,962 INFO     ERROR: (gcloud.auth.activate-service-account) There was a problem refreshing your current auth tokens: Unable to find the server at oauth2.googleapis.com
2018-10-04 13:54:42,963 INFO     Please run:
2018-10-04 13:54:42,963 INFO     
2018-10-04 13:54:42,963 INFO       $ gcloud auth login
2018-10-04 13:54:42,963 INFO     
2018-10-04 13:54:42,963 INFO     to obtain new credentials, or if you have already logged in with a
2018-10-04 13:54:42,963 INFO     different account:
2018-10-04 13:54:42,963 INFO     
2018-10-04 13:54:42,963 INFO       $ gcloud config set account ACCOUNT
2018-10-04 13:54:42,963 INFO     
2018-10-04 13:54:42,963 INFO     to select an already authenticated account to use.
```
(see attached log file for full output)
[logs_seqr_minikube.txt](https://github.com/macarthur-lab/seqr/files/2447572/logs_seqr_minikube.txt)

So I created my own service account key file and pasted the key into the `seqr/deploy/secrets/shared/gcloud/serve-account-key.json`.  This didn't make a difference though and I still receive the error after redeployment (step4). 

I wonder if the container is able to connect to the internet? Or do I need a payed gcloud account to download the resources this way? Sorry, I am new to gcloud. Maybe I am not activating my account in the right way.  I just want to deploy a local copy of seqr to use on our intranet/lab and avoid gcloud if possible.

Any suggestions?

Thanks,
Brian

**Comment by puapinyoying** [comment] 2018-10-04 20:18
hmm I let it run for a couple more hours and it was able to get seqr into a running state, but ran into this error deploying pipeline-runner.

```bash
2018-10-04 15:39:28,492 INFO     pipeline-runner is_running status = Pending
2018-10-04 15:39:33,590 INFO     pipeline-runner is_running status = Running
2018-10-04 15:39:33,591 INFO     ==> Deployed init-cluster, settings, secrets, mongo, postgres, external-elasticsearch-connector, kibana, redis, phenotips, seqr, pipeline-runner
2018-10-04 15:39:33,776 INFO     ==> kubectl exec  seqr-5b86bd5c54-m8m86 -- mkdir -p /seqr/data/reference_data
2018-10-04 15:39:34,014 INFO     ==> kubectl exec  seqr-5b86bd5c54-m8m86 -- wget https://storage.googleapis.com/seqr-reference-data/seqr-resource-bundle.tar.gz -O /seqr/data/reference_data/seqr-resource-bundle.tar.gz
Traceback (most recent call last):
  File "./servctl", line 288, in <module>
    update_reference_data(args.deployment_target)
  File "/home/brian/seqr/deploy/utils/loading_utils.py", line 120, in update_reference_data
    run_in_pod(pod_name, "wget https://storage.googleapis.com/seqr-reference-data/seqr-resource-bundle.tar.gz -O /seqr/data/reference_data/seqr-resource-bundle.tar.gz")
  File "/home/brian/seqr/deploy/utils/kubectl_utils.py", line 133, in run_in_pod
    run("kubectl exec %(it_arg)s %(full_pod_name)s -- %(command)s" % locals(), errors_to_ignore=errors_to_ignore, print_command=print_command, verbose=verbose, is_interactive=is_interactive)
  File "/home/brian/seqr/seqr/utils/shell_utils.py", line 98, in run
    raise RuntimeError(output)
RuntimeError: converted 'https://storage.googleapis.com/seqr-reference-data/seqr-resource-bundle.tar.gz' (ANSI_X3.4-1968) -> 'https://storage.googleapis.com/seqr-reference-data/seqr-resource-bundle.tar.gz' (UTF-8)
--2018-10-04 15:39:34--  https://storage.googleapis.com/seqr-reference-data/seqr-resource-bundle.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... failed: Name or service not known.
wget: unable to resolve host address 'storage.googleapis.com'
command terminated with exit code 4
```

The command `wget https://storage.googleapis.com/seqr-reference-data/seqr-resource-bundle.tar.gz -O /seqr/data/reference_data/seqr-resource-bundle.tar.gz` works through terminal. So I am wondering if the container is able to connect to the internet?

**Comment by bw2** [comment] 2018-10-04 21:54
Hi Brian, 
Thanks for the detailed description. I've added  google cloud sdk to the install script.

I've also seen the container internet connection issue - and fixed an underlying cause of it a couple weeks ago (by adding https://github.com/macarthur-lab/seqr/blob/master/deploy/step1.linux-centos7.install_dependencies.sh#L71-L96  and https://github.com/macarthur-lab/seqr/blob/master/deploy/step1.linux-centos7.install_dependencies.sh#L126-L127 ). One way the issue could come back is if the core-dns container gets evicted because the system is hitting resource limits - which would then cause dns lookups to fail and might also be the underlying reason for the google auth errors. To check if memory or other limits are causing these issues, you could run `kubectl get pods --all-namespaces` and see if any core-dns pods are in a state other than Running. If yes, running `kubectl -n kube-system describe pods <name of core-dns pod that crashed - eg. coredns-99b9bb8bd-mswp8> ` will print more details ). 

I've just committed some updates to the resource limits to reduce chances of pods getting killed due to hitting memory or disk limits. 
One remaining issue I'm going to work on is that the pipeline-runner docker image has gotten too big with the 2 VEP caches (GRCh37 & GRCh38), so docker takes a really long time to pull it in and can crash.  I'm going to try downloading the VEP caches on image strartup instead.

**Comment by puapinyoying** [comment] 2018-10-09 15:11
Hi Ben,

I saw that you made a few new commits, so I tried to redo the installation fresh and ran into some other issues.

1. The google cloud sdk still doesn't automatically install. This is what I found with some googling that works for me in centos7:

```bash
sudo tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
[google-cloud-sdk]
name=Google Cloud SDK
baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOM

# The indentation for the 2nd line of gpgkey is important.

# Install the Cloud SDK
sudo yum install -y google-cloud-sdk
```

2. I noticed that the step 3 install script generates another `start_elasticsearch.sh` script containing the `nohup` command won't work without declaring the elasticsearch variable inside the start script.  Without it it will show `.//bin/elasticsearch` doesn't exist

```bash
ELASTICSEARCH_VERSION=elasticsearch-6.4.0 # added

cd "/home/brian";
ES_JAVA_OPTS="-Xms3900m -Xmx3900m" nohup ./${ELASTICSEARCH_VERSION}/bin/elasticsearch -E network.host=0.0.0.0 | tee elasticsearch.log
```

3.  Finally, the big issue is that phenotips no longer starts. During Step 4.

```bash
...
2018-10-09 11:06:57,499 INFO     phenotips is_ready status = false
2018-10-09 11:07:02,575 INFO     phenotips is_ready status = false
2018-10-09 11:07:07,679 INFO     phenotips is_ready status = false
2018-10-09 11:07:12,787 INFO     phenotips is_ready status = false
```

I am seeing a few errors and failure in the log file, I grep'ed a few, they aren't all in order
```bash
2018-10-09 10:40:46,027 INFO     2018-10-09 14:40:34,655 [http://localhost:8080/bin/login/XWiki/XWikiLogin] ERROR c.x.x.s.DBCPConnectionProvider - Could not create a DBCP pool. There is an error in the Hibernate configuration file, please review it. 
2018-10-09 10:40:46,031 INFO     2018-10-09 14:40:34,658 [http://localhost:8080/bin/login/XWiki/XWikiLogin] ERROR c.x.x.w.XWikiAction            - Uncaught exception during XWiki initialisation: 
2018-10-09 10:40:46,031 INFO     com.xpn.xwiki.XWikiException: Error number 11007 in 0: Failed to extract Entity Resource Reference from URL [http://localhost:8080/bin/ServerError]
2018-10-09 10:40:46,033 INFO     Caused by: java.lang.RuntimeException: Failed to located wiki descriptor for alias [localhost]
2018-10-09 10:40:46,033 INFO     Caused by: org.xwiki.wiki.manager.WikiManagerException: Failed to locate XWiki.XWikiServerClass document for wiki alias [localhost]
2018-10-09 10:40:46,036 INFO     javax.servlet.ServletException: com.xpn.xwiki.XWikiException: Error number 11007 in 0: Failed to extract Entity Resource Reference from URL [http://localhost:8080/bin/ServerError]
2018-10-09 10:40:46,037 INFO     com.xpn.xwiki.XWikiException: Error number 11007 in 0: Failed to extract Entity Resource Reference from URL [http://localhost:8080/bin/ServerError]
2018-10-09 10:40:46,041 INFO     java.lang.RuntimeException: Failed to located wiki descriptor for alias [localhost]
2018-10-09 10:40:46,056 INFO     org.xwiki.wiki.manager.WikiManagerException: Failed to locate XWiki.XWikiServerClass document for wiki alias [localhost]
```

You can see a larger portion of the log attached.
[phenotips_error.txt](https://github.com/macarthur-lab/seqr/files/2460962/phenotips_error.txt)

**Comment by bw2** [comment] 2018-10-09 22:08
Thanks for troubleshooting. I've added your corrections 1 and 2, but haven't yet been able to reproduce the 3rd issue. I'm running step4.install_seqr_on_minikube.sh on a clean CentOS7 VM on google cloud. It calls ```./servctl deploy-all --restore-seqr-db-from-backup gene_reference_data_backup.gz --docker-image-tag release_20180926 minikube```
 
[deploy-all-log.txt](https://github.com/macarthur-lab/seqr/files/2462384/deploy-all-log.txt)

Let me see if I can reproduce it with an image that includes the latest commits...

**Closed** 2019-03-14 18:31 UTC
