### ISSUE TITLE
Editing Seqr Families

### ISSUE THREAD

**Issue by shall48** [macarthur-lab/seqr#1391] opened 2020-07-23 16:09 UTC
I am trying to make some edits to seqr families in one project. When I try to delete a sample from a family I get an error message the first time and then it works the second time. I have tried this for a few families and keep encountering the same issue within the edit families and individuals section of the CMG_Sherr_Exomes project https://seqr.broadinstitute.org/project/R0474_cmg_sherr_exomes/project_page. I just want to make sure that I am in fact deleting certain individuals accurately.

-Stacey Hall

**Comment by hanars** [comment] 2020-07-23 17:00
Hi Stacy,

When submitting a github issue, its really important to fill out the template, as this ensures that I have all the information I need to solve the issue without lots of back and forth: https://github.com/macarthur-lab/seqr/issues/new?assignees=&labels=bug&template=bug_report.md&title=

Some things that I need for this ticket before I can proceed are: 
- Information about the scope of the bug - did you try this in other projects and if so did it work or not? If you didn't check  thats okay, I just need to know
- screenshots of the error(s)
- what **exactly** you did to get the error - what do you mean by "delete a sample"? Which exact buttons/ pages are you using to do that? Often the screenshot will show a lot of this information

**Comment by shall48** [comment] 2020-07-23 20:05
Hi Hana,

Sorry about that.

1. I did not try this in other projects.
2. We had to repatient some samples and now we have duplicates and unknown
samples that we do not want in seqr. Thus, I was removing them from the
projects one by one. Ex: SHE_1231M_1 was not the mother sample, but was a
duplicate of the proband. SHE_1231M_1 been repatiented to be SHE_1231P_D2.
I wanted to then remove SHE_1231M_1 from seqr because we don't want the
duplicates. I erased the maternal ID for the proband and clicked apply.
Then I went back in to delete SHE_1231M_1, but this is the error message I
keep getting. If I go back in it allows me to then delete the sample, but I
have done this for 5 other samples and before I continue I just want to
make sure I'm doing this accurately.

Thanks,
Stacey
[image: Screen Shot 2020-07-23 at 3.59.11 PM.png]

**Comment by hanars** [comment] 2020-07-23 20:29
Thanks for the update! An unfortunate thing with github is if you respond to the email with a screenshot it doesn't actually add the image to the ticket for me, it just shows the text "[image: Screen Shot 2020-07-23 at 3.59.11 PM.png]". Please go to the link for the original ticket and add the screenshot there

**Comment by shall48** [comment] 2020-07-23 20:41
<img width="1440" alt="Screen Shot 2020-07-23 at 3 59 11 PM" src="https://user-images.githubusercontent.com/61699565/88336634-59002880-cd03-11ea-9757-a12d5f380b4d.png">

**Comment by hanars** [comment] 2020-07-23 22:32
This should be fixed now! Can you try again and see if the issue is still happening

**Closed** 2020-07-27 14:24 UTC
Labels: bug
